[phases.setup]
nixPkgs = ['nodejs-22_x']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node src/index.js'

[variables]
NODE_ENV = 'production'
